products/urls.py
from django.urls import path
from .views import ProductsList,ProcuctDetail,BrandList,BrandDetail,CategoryList

app_name = 'products'

urlpatterns = [
    path('', ProductsList.as_view(),name='product_list'),
    path('<int:pk>', ProcuctDetail.as_view(),name='product_detail'),
    path('brand/', BrandList.as_view(),name='brand_list'),
    path('brand/<int:pk>', BrandDetail.as_view(),name='brand_detail'),
    path('category/', CategoryList.as_view(),name='category_list'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/',include('products.urls', namespace='products')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models

# Create your models here.

products/models.py
from distutils.command.upload import upload
from email.mime import image
from django.utils import timezone
from django.db import models
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
# Create your models here.
PRODUCT_FLAG={
    ('new','new'),
    ('feature','feature'),
    ('sale','sale'),
    ('old','old'),
}

class Product(models.Model):
    name = models.CharField(_('Name'),max_length=100)
    sku = models.IntegerField(_('Sku'))
    suptitle = models.CharField(_('Subtitle'),max_length=300)
    desc = models.TextField(_('Description'),max_length=10000)
    flag = models.CharField(_('Flag'), max_length=10, choices=PRODUCT_FLAG)
    price = models.IntegerField(_('Price'),default=1)
    image = models.ImageField(_('Image'),upload_to='prodect-image/%y/%m/%d')
    tags = TaggableManager()
    brand = models.ForeignKey('Brand',verbose_name=_('Brand'), related_name='product_brand',on_delete=models.SET_NULL,null=True,blank=True)
    category = models.ForeignKey('Category',verbose_name=_('Category'), related_name='product_category',on_delete=models.SET_NULL,null=True,blank=True)
    vedio = models.URLField(null=True,blank=True)


    def __str__(self) -> str:
        return self.name


class ProductsImages(models.Model):
    product = models.ForeignKey(Product,verbose_name=_('Product'), related_name='product_images',on_delete=models.CASCADE)
    image = models.ImageField(_('Image'),upload_to='prodect-image/%y/%m/%d')

    def __str__(self) -> str:
        return str(self.product)


class Category(models.Model):
    name = models.CharField(_('Name'),max_length=100)
    image = models.ImageField(_('Image'),upload_to='category/%y/%m/%d')

    def __str__(self) -> str:
        return self.name


class Brand(models.Model):
    name = models.CharField(_('Name'),max_length=100)
    image = models.ImageField(_('Image'),upload_to='brand/%y/%m/%d')

    def __str__(self) -> str:
        return self.name


class ProductsReview(models.Model):
    user = models.ForeignKey(User, verbose_name=_('User_Review'), on_delete=models.SET_NULL, null=True, blank=True)
    product = models.ForeignKey(Product, verbose_name=_('Product'), on_delete=models.SET_NULL, null=True, blank=True)
    rate = models.IntegerField(verbose_name=_('Rate'))
    review = models.CharField(verbose_name=_('Review'), max_length=200)
    created_at = models.DateTimeField(default = timezone.now)

    def __str__(self) -> str:
        return str(self.user)

settings/models.py
from django.db import models

# Create your models here.
class Company(models.Model):
    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='company/%y/%m/%d')
    subtitle = models.CharField(max_length=500)
    fb_link = models.URLField(null=True,blank=True)
    insta_link = models.URLField(null=True,blank=True)
    tw_link = models.URLField(null=True,blank=True)
    address = models.TextField(max_length=500)
    phone_numper = models.TextField(max_length=500)
    email = models.TextField(max_length=500)
    call_us = models.CharField(max_length=500)
    email_us = models.EmailField()
    
    def __str__(self) -> str:
        return self.name
    

accounts/views.py
from django.shortcuts import render

# Create your views here.

orders/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from multiprocessing import context, get_context
from django.db.models import Count
from django.views.generic import ListView,DetailView
from .models import Category, Product, ProductsImages, Brand
# Create your views here.

class ProductsList(ListView):
    model = Product


class ProcuctDetail(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        myproduct = self.get_object()
        context['images'] = ProductsImages.objects.filter(product=myproduct)
        context['related'] = Product.objects.filter(category=myproduct.category)[:10]
        return context

class BrandList(ListView):
    model = Brand


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['brands'] = Brand.objects.all().annotate(product_count=Count('product_brand'))
        return context

class BrandDetail(DetailView):
    model = Brand

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        brand = self.get_object()
        context['brand_product'] = Product.objects.filter(brand=brand)
        return context

class CategoryList(ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all().annotate(product_count=Count('product_category'))
        return context

settings/views.py
from django.shortcuts import render

# Create your views here.

products/templates/products/brand_detail.html
{% extends "base.html" %}
{% load static %}

{% block myextend %}
    <link rel="stylesheet" href="{% static 'css/brand-single.css'%}">
{% endblock myextend %}

{% block body %}

        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>Brand Single</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="brand-list.html">brand-list</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-single</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                  BRAND SINGLE PART START
        =======================================-->
        <div class="brand-single">
            <a href="#"><img src="{{brand.image.url}}" alt="brand"></a>
            <a href="#"><h3>{{brand.name}}</h3></a>
            <ul>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star"></li>
                <li class="total">(163 ratings)</li>
            </ul>
            <p>({{brand.product_count}} items)</p>
        </div>
        <!--=====================================
                  BRAND SINGLE PART END
        =======================================-->


        <!--=====================================
                    SHOP PART START
        =======================================-->
        <section class="inner-section shop-part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-5">
                {% for product in brand_product %}
                    <div class="col">
                        <div class="product-card">
                            <div class="product-media">
                                <div class="product-label">
                                    <label class="label-text new">{{product.flag}}</label>
                                </div>
                                <button class="product-wish wish">
                                    <i class="fas fa-heart"></i>
                                </button>
                                <a class="product-image" href="product-video.html">
                                    <img src="{{product.image.url}}" alt="product">
                                </a>
                                <div class="product-widget">
                                    <a title="Product Compare" href="compare.html" class="fas fa-random"></a>
                                    <a title="Product Video" href="{{product.vedio}}" class="venobox fas fa-play" data-autoplay="true" data-vbtype="video"></a>
                                    <a title="Product View" href="#" class="fas fa-eye" data-bs-toggle="modal" data-bs-target="#product-view"></a>
                                </div>
                            </div>
                            <div class="product-content">
                                <div class="product-rating">
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="icofont-star"></i>
                                    <a href="product-video.html">(3)</a>
                                </div>
                                <h6 class="product-name">
                                    <a href="{% url 'products:product_detail' product.id %}">{{product}}</a>
                                </h6>
                                <h6 class="product-price">
                                    <del>$34</del>
                                    <span>{{product.price}}<small>/piece</small></span>
                                </h6>
                                <button class="product-add" title="Add to Cart">
                                    <i class="fas fa-shopping-basket"></i>
                                    <span>add</span>
                                </button>
                                <div class="product-action">
                                    <button class="action-minus" title="Quantity Minus"><i class="icofont-minus"></i></button>
                                    <input class="action-input" title="Quantity Number" type="text" name="quantity" value="1">
                                    <button class="action-plus" title="Quantity Plus"><i class="icofont-plus"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                                <li class="page-item"><a class="page-link active" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">...</li>
                                <li class="page-item"><a class="page-link" href="#">60</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    SHOP PART END
        =======================================-->
        
{% endblock body %}

products/templates/products/brand_list.html
{% extends "base.html" %}
{% load static %}

{% block body %}


        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>brand list</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-list</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    BRAND LIST PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select isotope-select">
                                    <option value="*">show all</option>
                                    <option value=".vegetables">vegetables</option>
                                    <option value=".fruits">fruits</option>
                                    <option value=".drinks">drinks</option>
                                    <option value=".fishes">fishes</option>
                                    <option value=".meats">meats</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 isotope-items">
                {% for brand in brands %}
                
                
                    <div class="col all vegetables">
                        <div class="brand-wrap">
                            <div class="brand-media">
                                <img src="{{brand.image.url}}" alt="brand">
                                <div class="brand-overlay">
                                    <a href="brand-single.html"><i class="fas fa-link"></i></a>
                                </div>
                            </div>
                            <div class="brand-meta">
                                <h4>{{brand.name}}</h4>
                                <p>({{brand.product_count}} items)</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                                <li class="page-item"><a class="page-link active" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">...</li>
                                <li class="page-item"><a class="page-link" href="#">60</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    BRAND LIST PART END
        =======================================-->
{% endblock body %}

products/templates/products/category_list.html
{% extends "base.html" %}
{% load static %}
{% block body %}


        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>all category</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">all-category</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    CATEGORY PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 justify-content-center">
                {% for cat in category %}
                    <div class="col">
                        <div class="category-wrap">
                            <div class="category-media">
                                <img src="{{cat.image.url}}" alt="category">
                                <div class="category-overlay">
                                    <a href="{% url 'products:product_list' %}"><i class="fas fa-link"></i></a>
                                </div>
                            </div>
                            <div class="category-meta">
                                <h4>{{cat.name}}</h4>
                                <p>({{cat.product_count}} items)</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                                <li class="page-item"><a class="page-link active" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">...</li>
                                <li class="page-item"><a class="page-link" href="#">60</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    CATEGORY PART END
        =======================================-->

{% endblock body %}